### ISSUE TITLE
Suppress all log content

### ISSUE THREAD

**Issue by mfeblowitz** [IBM/forbiditerative#12]
After setting `--suppress-planners-output`, there are still several items being emitted:

<img width="553" alt="Screenshot 2023-07-10 at 12 59 48 PM" src="https://github.com/IBM/forbiditerative/assets/6854939/de472c3b-e41f-42ff-9031-404fd72eef6b">

I have also looked at ways to set the log level, but there don't seem to be viable options in the defined arguments.

Is there a way to suppress these items? If not, please consider this a request...

**Comment by ctpelok77** [comment]
Resolved
