### ISSUE TITLE
pip install conflicting builds location between _custom_build.py and build.py 

### ISSUE THREAD

**Issue by James-Oswald** [IBM/forbiditerative#9]
# Environment 
Tested on two separate operating systems, same issue on both:
* Ubuntu 20.04 with python 3.8 with pip
* Redhat Red Hat Enterprise Linux release 8.7 with pipenv  
# Problem
When installing as a python package with:
```bash
pip install git+https://github.com/IBM/forbiditerative.git
```
This directory structure is created in the python packages path, as specified in `_custom_build.py`.
```
site-packages
├── driver
└── forbiditerative
    └── builds
```
Then when then trying to run the module using:
```
python -m forbiditerative.plan ...args
```
The following error occurs: 
```
Could not find build 'release' at /usr/local/lib/python3.8/dist-packages/builds/release/bin. Please run './build.py release'.
```
This is because `driver/util.py`'s BUILDS_DIR, expects the following structure as it is created by `build.py` to function properly:
```
site-packages
├── driver
├── forbiditerative
└── builds
```
but this is not the same structure that is created by _custom_build.py which is run during the pip install. 

### Current workarounds
There are a few temporary workarounds I've tested for the end user:
1) builds can be manually moved
```bash
cd .../site-packages/
mv forbiditerative/builds builds
```
2) `driver/util.py` can be modified to take this path change in account:
```py
DRIVER_DIR = os.path.abspath(os.path.dirname(__file__))
REPO_ROOT_DIR = os.path.dirname(DRIVER_DIR)
BUILDS_DIR = os.path.join(REPO_ROOT_DIR, "forbiditerative", "builds")
```

### Proposed Fixes
There are two possible permanent fixes that could remedy this issue:
1) Not recommended but possible: change `_custom_build.py` to install builds in the expected path as `./build.py` does (probably not a good idea as this would place a non-module directory with the ambiguous name "builds" in the python module path) or
2) My recommendation: add a check into `driver/util.py` that looks for builds in `forbiditeritive/builds` where  `_custom_build.py` currently installs it.

I would be happy to try implementing option 2 as a fix if assigned.

**Comment by illeatmyhat** [comment]
This is because, when running as a library, a `--build` parameter is expected, so if attempting to use the library functions with the CLI, it should be e.g.
```bash
python -m forbiditerative.plan \
--build $(python -c 'import site; print(site.getsitepackages()[0])')/forbiditerative/builds/release/bin \
--planner topk --domain examples/logistics00/domain.pddl --problem examples/logistics00/probLOGISTICS-4-0.pddl --number-of-plans 1000 --symmetries --use-local-folder --clean-local-folder --suppress-planners-output
```
should work for you.

Everything in the `/driver` folder is derived from the upstream https://github.com/aibasel/downward so I don't recommend making changes there.

**Comment by illeatmyhat** [comment]
sounds good to me. @ctpelok77 do you agree?
FYI this is usually how I find the build folder.
```python
from pathlib import Path
import forbiditerative

build_dir = Path(forbiditerative.__file__).parent / 'builds' / 'release' / 'bin'
```
It's important to note that when you do `pip install -e .`, the forbiditerative module will point to the cloned repo rather than setup-packages.

**Comment by James-Oswald** [comment]
Just tested as a library and yes 
```bash
python3 -m forbiditerative.fast-downward ...args
```
gives same behavior with the error that the builds are not found.

But since `fast-downward.py` takes a `--build` argument to the binaries as well, I should be able to reuse the same process of injecting a default value for build directory based on its existence in either the python package or the repo. In the case of `plan.py` I would be injecting into an argparse namespace, while in `fast-downward.py` I would presumably need to modify `sys.argv` directly since argument parsing for fast-downward is handled in the upstream driver.
